name: Test
on: push

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest]
            test: [a b, c d]
            exclude:
              - test: c d
        fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - run: echo "GOT RUN"
        if: ${{ !matrix.test }}
