name: Test
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo $VERSION
          echo $VERSION2
          echo $VERSION3
      - env:
          VERSION: ${{ github.ref }}
          VERSION2: ${{ github.head_ref }} 
          VERSION3: ${{ github.base_ref }}
