name: Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: macos-13-large
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - run: pip install pipenv && pipenv install boto3
        env:
          VERSION: ${{ github.ref }}
          VERSION2: ${{ github.head_ref }} 
          VERSION3: ${{ github.base_ref }}
          VERSION4: ${{ github.head_ref || 'master' }}
      - run: pipenv run python -c "import os; print(os.getenv('VERSION'))"
        env:
          VERSION: ${{ github.ref }}
      - run: python -c "import os; print(os.getenv('VERSION'))"
        env:
          VERSION: ${{ github.ref }}
