name: Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'
      - run: |
          go install sigs.k8s.io/kind@v0.12.0
          go install github.com/cloudflare/cfssl/cmd/...@latest
          kind create cluster --wait 30s
          kubectl config use-context kind-codalab
          kubectl get pods --output=jsonpath={.items..metadata.name}
          for c in $(kubectl get pods --output=jsonpath={.items..metadata.name}); do echo $c; done
