name: Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - run: pip install --upgrade selenium==3.141.0
      - run: python -c "import selenium; print(selenium.__version__)"
      - run: geckodriver --version && chromedriver --version
      - run: sudo ./scripts/test-setup.sh && export PATH=$PATH:$PWD/geckodriver
      - run: geckodriver --version && chromedriver --version
      - run: echo $VERSION && echo $VERSION2 && echo $VERSION3 && echo $VERSION4
        env:
          VERSION: ${{ github.ref }}
          VERSION2: ${{ github.head_ref }} 
          VERSION3: ${{ github.base_ref }}
          VERSION4: ${{ github.head_ref || 'master' }}
