name: Test
on: push

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest]
            test: [a b,c d]
            x: [true, false]
            exclude:
              - test: a b
                x: true
        fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - run: ls $GECKOWEBDRIVER
      - run: ls $CHROMEWEBDRIVER
      - run: which geckodriver
