name: Test
on: push

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest]
            test: [a, b, c, d]
        fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - run: |
          git clone https://github.com/codalab/codalab-worksheets.git
          cd codalab-worksheets
          python3 codalab_service.py pull --version gha
          python3 codalab_service.py start --services default monitor --version gha
          python3 test_runner.py --version gha frontend
